package.json
Upstream meson promotes to use `builddir` instead of `build`, see [this commit](https://github.com/mesonbuild/meson/commit/f3be687cbbfd1ff25c7ec4ffe8ba4adfee9a6579). This extension should follow that recommendation for the default build directory.
=> change default build folder to builddir

package.json
Flat is barely supported, and doesn't work in a lot of cases. It should
absolutely not be set by default.
=> Remove layout=flat from default options

syntaxes/meson.tmLanguage.json
Add new meson functions to the syntax highlighting, as applied to upstream repository to fix https://github.com/asabil/vscode-meson/issues/14
=> Apply recent changes from upstream source

package.json, src/utils.ts
Since the package has moved into the meson project namespace. I've made
the "author" name the meson project, and added contributors for the the
other entries.
=> Update names to point to mesonbuild instead of asabil

package.json, src/extension.ts, src/meson/introspection.ts, src/meson/runners.ts, src/tasks.ts, src/treeview/nodes/targets.ts, src/utils.ts, yarn.lock
Hi
Great that this extension is now part of the meson project and will hopefully get some love.
Here are some patches to fix a few issues with spaces in test target names and to use `meson` rather than `ninja` for all commands (I use `samurai`).
I other less trivial ones but thought I'd see if these are of interest first.
Regards
=> Fixes when there are spaces in test target name

src/treeview/index.ts
Broken in b24c9a23, by the looks of it.
```
stack trace: Error: command 'mesonbuild.targets-refresh' not found
at h._tryExecuteCommand (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1501:3364)
at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1501:3245
at processTicksAndRejections (internal/process/task_queues.js:93:5)
```
=> fix: wrong command name used by MesonProjectExplorer.refresh().

package.json, src/extension.ts, src/meson/introspection.ts, src/meson/runners.ts, src/tasks.ts, src/treeview/nodes/tests.ts, src/treeview/nodes/toplevel.ts
Meson itself doesn't seem to mind tests and benchmarks having the same name. The extension doesn't allow it, though (or rather just fails to add benchmark nodes to the tree view due to duplicate node id).
Here's a fix and it also separates out benchmarks in to a new top level node, which I think looks nicer.
It also uses `--verbose` for running benchmarks as the output is generally of interest. But maybe that should be a config option?
And a few other tidy ups.
Cheers
=> Fix when tests and benchmarks have the same name

package.json, src/extension.ts
Here's an update of #31 so it applies cleanly and some tidy ups.
BTW there's still some issues with the prompt in that if you open a workspace that has no meson.build and accidentally hit F1 -> Meson -> Build the extension is activated so it pops up (and then the pick target prompt just sits there). Lots of activation events other than `meson.build`...
```
"activationEvents": [
"onLanguage:meson",
"onCommand:mesonbuild.configure",
"onCommand:mesonbuild.build",
"onCommand:mesonbuild.test",
"onCommand:mesonbuild.benchmark",
"workspaceContains:meson.build"
],
```
=> Refactor configure prompt

src/extension.ts, src/utils.ts
Per #59.
There's two commits here - first is a quick fix to change the "publisher.package" string that was broken by the package name change.
Second commit caches the extension's path from activation. Decouples from the name of the extension (and saves all those calls to getExtension()), though I don't really like having a globalish like that.
Looking at all the uses, it shouldn't be too much work to refactor to pass the extension context through to where it's needed. I don't mind looking at that if commit 2 isn't palatable, but at least the first commit should fix the problem for now!
Cheers
=> Fix extension path

src/treeview/nodes/toplevel.ts
They are currently uninteresting as you can't do anything with them so I think this is nicer.
=> refactor: move subprojects to bottom of top level node.

src/extension.ts
Small tidy up to stop using deprecated `vscode.workspace.rootPath` (plus stylistically bad merge conflict resolution by me for the previous version...).
=> refactor: updated some deprecated vscode stuff.

src/utils.ts
Currently it's treated not as an absolute one, but as a relative to the workspace.
So `/tmp/project-build` resolves to `<WORKSPACE_FOLDER>/tmp/project-build`.
[`path.resolve`](https://nodejs.org/api/path.html#pathresolvepaths) will take care of that.
=> fix: correctly process absolute path in `mesonbuild.buildFolder`

package.json, src/configprovider.ts, src/extension.ts, src/treeview/index.ts
Planned todo: Add the build task of the debugged executable as preLaunchTask to force a rebuild.
Shares the first commit with https://github.com/mesonbuild/vscode-meson/pull/57
supersedes https://github.com/mesonbuild/vscode-meson/pull/23 IMO
Fixes #21
=> Add debug configuration provider

package.json, src/extension.ts, src/meson/introspection.ts, src/meson/runners.ts, src/tasks.ts, src/types.ts
This merges #29 and updates the changes for new developments that happened since.
Notably, it removes the ninjaPath configuration again, since ninja isn't invoked directly anymore.
While this and #57 don't collide, they need to be updated when one is pulled, since there's a new invocation for tests.
closes #29
=> Add mesonpath

src/extension.ts, src/meson/introspection.ts, src/meson/types.ts, src/tests.ts
While the code in this works fine, I think there's a couple of things that I'd want some feedback on first.
Mainly:
* Debug runner:
* should we try harder to pipe the result back into tests?
* should we try to prevent debugging non-c(++) targets? This would require some heuristics (on dependencies) I think. 
* Testing runner:
* should we run tests in series to avoid the testlog issue?
* If not, should we fail the tests that couldn't be run? Maybe set all to skipped, that's a state vscode supports
Other than that, just general review :) 
Commits are messy, but this grew while learning^^
closes #23
=> Integrate with the native testing API (including debug)

src/tests.ts
As mentioned in #66, #57 introduced more uses of calling into meson, that could use the update to the config option.
=> fix: Use "mesonPath" in test provider

src/meson/runners.ts
When using more than one argument for setup, they all get concatenated together, making the first one the only recognized and its parameter being the concatenation of all the rest of the lines.
=> Fix concatenation of multiple arguments

README.md
=> replace "provider" with a link to muon in README

src/meson/runners.ts
Using the tasks to build from the meson.build command. Making it in line with the other commands.
=> Simplifying build, using build tasks

package.json, src/extension.ts, src/treeview/nodes/targets.ts
The treeview will have an open-file button for each target.
This will open the build.meson file where the target is defined.
=> Can open meson.build from treeview

package.json, src/meson/runners.ts, src/types.ts
=> add setupOptions configuration, useful for passing --cross-file to meson setup

src/formatters.ts, src/linters.ts, src/tools/muon.ts, src/types.ts
Pass around a `Tool` that consists of a version + a path, so that the linting / formatting functions can alter their behavior based on version.  Also, make the version check for muon smarter.
=> update tool version handling

src/meson/runners.ts
Reconfiguring a project can be slow, especially when having lots of subprojects. Once the project has been configured, there is no reason to reconfigure it on startup, a rebuild will reconfigure only if needed.
=> Do not reconfigure on vscode startup

src/configprovider.ts, src/tests.ts, src/tools/muon.ts
Some files are not correctly formatted based on the .editorconfig definitions.
=> Apply format defined in .editorconfig

package.json, src/configprovider.ts
It is causing the extension to fail to activate:
```
[error] Activating extension mesonbuild.mesonbuild failed due to an error:
[error] Error: Cannot find module 'vscode-nls'
```
There seems to be a new mechanism with vscode-l10n but since we were not doing translations anyway, let's drop it for now.
=> Remove vscode-nls

package.json
E.g. for errors in system-wide includes.
=> Use autodetect for meson-gcc problem matcher.

package.json
Also change the text to "Open meson.build" for the tooltip.
=> Don't show "Open" (meson.build) in command palette.

package.json, src/extension.ts, src/tasks.ts, src/types.ts
This adds a new command named `Meson: Run Executable` that lets the user select from a list of all the executables targets and run one of them, similar to how `Meson: Run Unit Tests` works.
CC @xclaesse
=> Add a new command to run executables

src/treeview/nodes/toplevel.ts
Meson does not require a version to be set in the project() call. When a version is not set, Meson sets the version as "undefined" in the introspection data.
=> Fix version showing "undefined" in tree view

package.json, src/extension.ts
Following on from #134
FWIW. Very sledgehammer / nut. I can't see a trivial and more fine-grained approach (e.g. just deactivate/reactivate extension) and given I want to rebase code that already decouples builddir, I don't really want to look any further. 
That said I did see this: https://github.com/microsoft/vscode/issues/45774#issuecomment-373423895
=> extension: reload window if buildFolder changes.

package.json, src/tasks.ts, src/types.ts
Being able to run tests with `--verbose` is sometimes useful.
Maybe `testOptions` (and a separate `benchmarkOptions`) is a better more generic approach?
=> Add test and benchmark options

src/extension.ts, src/utils.ts
The ccache bug has been fixed upstream:
https://github.com/microsoft/vscode-cpptools/issues/7616
=> Don't patch compile_commands.json any more

CHANGELOG.md, src/extension.ts
The tests list in the tests controller is only updated when a change is detected. It's now done on activation  to list all tests from the beginning.
=> List tests on activation

CHANGELOG.md, src/tasks.ts
The list of runnable executables excludes not installed executables to filter out tests, but this also filters out other executables like examples. Instead, cross-chech with the tests array to remove only tests
=> tasks: list examples as runnable executables

CHANGELOG.md, package.json, src/extension.ts, src/lsp/common.ts, src/lsp/index.ts, src/lsp/swift-mesonlsp.ts, src/storage.ts, src/types.ts, yarn.lock
=> Add integration for Swift-MesonLSP

package.json
These can be removed with an engine bump. Also fixes the engine version format, which will remove the generated warning.
=> Remove various unnecessary activation events

CHANGELOG.md, package.json, src/configprovider-cppdbg.ts, src/configprovider-lldb.ts, src/configprovider.ts, src/extension.ts, src/tests.ts
Currently, the vscode-meson extension is hardcoded to support only Microsoft's C/C++ extension, which provides the `cppdbg` debugger. However, using the Microsoft extension may not be preferable. An alternative extension, CodeLLDB (https://github.com/vadimcn/codelldb), also provides C/C++ support, including the `lldb` debugger.
These changes add a second debug configuration provider that works with the `lldb` debugger.
These changes also introduce an extension availability check when trying to run tests with debugging. Both the `cppdbg` and `lldb` debuggers are supported, in that order. In addition, a proper error message is now displayed instead of the cryptic "Configured debug type 'cppdbg' is not supported" when no debuggers are available.
Note: The `lldb` debug configuration sets the …
=> Add support for CodeLLDB extension

CHANGELOG.md, src/extension.ts, src/lsp/index.ts
Configuration format is like this in your .settings.json
```
{
"mesonbuild.Swift-MesonLSP": {
"others": {
"ignoreDiagnosticsFromSubprojects": true,
},
"linting": {
"disableNameLinting": true,
"disableCompilerIdLinting": true,
}
}
}
```
Testing:
- Remove downloaded language server from the vscode extension
- Use binaries from HEAD of https://github.com/JCWasmx86/Swift-MesonLSP and drop them in PATH
- Use e.g. https://github.com/hse-project/hse
Your diagnostics will look like this:
Merge the config listed above with your .settings.json.
Only this error will be left:
(A bug on my side, as my heuristics will never be able to guess the sophisticated subdir calculation for hse-python, but that's offtopic here)
Only thing missing here is the auto-completion/diagnostics in the settings.json file.
=> Send configuration fo mesonbuild to language server, if it changed

package.json
Allows improved visibility of these options, diagnostics, docs and auto-completion.
Draft, as I'm not sure whether these descriptions make sense for people that don't know about the language server/don't know the exact details
=> Add all Swift-MesonLSP configs to package.json

package.json, src/extension.ts, src/tasks.ts, src/tests.ts, src/utils.ts
This PR allows the `meson.build` file to be placed in a subdirectory within the workspace.
The current behavior of the extension is inconsequential, as some checks already look for `meson.build` in the entire workspace, and the activation event fires when you manually open `meson.build` that is stored in a subdirectory, resulting in a prompt to configure the workspace. Of course, there's no support for such behavior within the extension, so things fail.
This is similar to #22, but works automatically. No user-facing configuration option is exposed. If multiple `meson.build` files are found in the workspace, the 'first' one is used. I plan to extend this to allow the user to switch between different `meson.build` configurations within the same workspace, but this PR is a prerequisite for …
=> Enable storage of meson.build in a non-root directory in the workspace

src/extension.ts, src/formatters.ts, src/tools/muon.ts
Any reason not to do this? Allows a workspace root relative muon config file path.
Thanks
=> Run muon format from root of workspace.

src/lsp/index.ts
In the case the custom path to the language server is relative, look it up in `PATH` first. Useful if the name of the language server is `swift-mesonlsp` instead of `Swift-MesonLSP`.
=> Look up relative paths to the language server in `PATH` first

src/utils.ts
In Windows when running the plugin with the MSYS2 Meson package, the plugin throws the error "Meson version doesn't match expected output:". After some investigation I found that the response from `execFile` was returning: `error: null`, `stdout: ""` and `stderr: "1.3.0"`. I was unable to replicate this behavior in a shell, so I updated `execFile` to use "shell" mode by default, which solves the issue.
This seems to be specific to the MSYS2 package of meson, since using the pip version runs fine. However, since this is such a simple change that should not affect functionality, I thought I'd submit it.
=> Use shell mode for executing commands

src/extension.ts, src/utils.ts
This is very similar case than compile_commands.json, Meson generates a file in builddir that some extensions should be using. It makes static analysers work out of the box instead of requiring user to configure paths themself.
We only need to watch for file creation, it was previously wrongly watching for file changes for legacy reasons (we used to patch compile_commands.json).
=> Make sure rust-analyser uses rust-project.json Meson generates

src/utils.ts
Previous implementation was way too naive.
=> Sort root Meson files by number of path components

package.json, src/dialogs.ts, src/extension.ts, src/types.ts, src/utils.ts
There were many issues, including:
- The most common case is to have a meson.build at the root of the workspace. In that case we should not ask user anything.
- Only the first meson.build in a subdir tree is useful, others are unlikely to be projects.
- We need a way to never ask again to select a meson file, especially important when opening meson project itself which does not have a meson.build at the root, but many projects in test cases.
- If the user cancels selection, the meson extension cannot do anything and should be hidden.
- Selecting a meson file and configuring the project are 2 distinct questions. The user may want to select a file but not let vscode configure it. It is common to configure from an external terminal.
=> Refactor support for multiple Meson projects

src/tasks.ts, src/utils.ts
ProcessExecution() does not lookup into PATH.
Fixes: #181
=> Resolves mesonPath to program absolute path

CHANGELOG.md, src/utils.ts
=> Allow root meson.build files to be symlinks

src/utils.ts
Bitwise check for File or Directory type to properly handle symlinks of both
* Follow up for: #208
Testing:
- symlinked root `meson.build` gets picked up automatically
- symlinked directory with `meson.build` appears in the `Select configuration to use` prompt if there's no root `meson.build`
- regular files and directories still work
- (symlinked) directory named `meson.build` doesn't get picked up as root configuration
Based on [this sample](https://github.com/microsoft/vscode-extension-samples/blob/main/nodefs-provider-sample/src/extension.ts#L267).
=> utils: fix symlink handling in mesonRootDirs

CHANGELOG.md, package.json, src/introspection.ts, src/tasks.ts, src/tests.ts, src/types.ts, src/utils.ts
This adds two options, `configureEnvironment` and `testEnvironment`, allowing users to set particular environment variables during `meson setup` and `meson test`.
Closes: #9
=> Environment variables for setup and test tasks

CHANGELOG.md, src/lsp/mesonlsp.ts
Diff: https://github.com/JCWasmx86/mesonlsp/compare/v4.1.8...v4.2.2
Furthermore there could be Linux AArch64 support, but I'm not sure how good those work, as `mesonlsp` only compiles and passes my small testsuite on this Arch/OS combination
=> Bump to v4.2.2

package.json
Searching the entire workspace can be very costly, especially if the workspace is on a network drive. This change makes the extension assume that meson.build is located either in the workspace's root or in any directory two levels down from the root.
Potentially fixes #234.
=> Limit the depth of the meson.build search

src/tests.ts, src/types.ts
The C++ debugger requires "environment" key in the format
[ { "name": "config", "value": "Debug" } ]
https://code.visualstudio.com/docs/cpp/launch-json-reference
Note: I think [Javascript](https://code.visualstudio.com/docs/editor/debugging) uses 'env'. [Python](https://code.visualstudio.com/docs/python/debugging#_env) uses 'env'. Annoying. This patch doesn't account for Javascript or Python. Not sure if that is a problem.
Fixes #240
=> Pass environment to the testing debugger

src/utils.ts
=> Fix failure to run executable targets on Windows

src/tests.ts
Previously running a test which contained a space in its name, ie `command line parsing` would result in the test runner printing 
```
ERROR: *:command test name does not match any test
```
This encloses the test name in quotes so its parsed correctly on the command line.
=> Fix tests with spaces in their names not executing when ran from the testing ui

CHANGELOG.md, src/lsp/mesonlsp.ts
Diff: https://github.com/JCWasmx86/mesonlsp/compare/v4.2.2...v4.3.0
- Add support for specifying custom `subproject_dir` (top level directory name that holds Meson subprojects) (by @fourdim)
- Fix code formatting duplicating the last line when meson.build has fewer lines
- Fix malformed entries in completion list
- Deduplicate completion list
- Fix missing error, if an unknown variable is used as argument for a kwarg with the same name as the kwarg itself.
- Add missing constants from reference tables (by @blue42u)
- Add partial support for `str.replace()` in the interpreter (Fixes parsing of [Lix](https://git.lix.systems/lix-project/lix))
- Update API compat to 1.5.0rc1
=> Bump to v4.3.0

CHANGELOG.md, src/lsp/mesonlsp.ts
- Bumps mesonlsp to 4.3.2
- Regroups the values according to the filename to reduce the probability of errors while updating the hashes
=> Bump to v4.3.2

CHANGELOG.md, src/lsp/mesonlsp.ts
- Propagate wrap setup errors to the editor (E.g. invalid .ini file syntax)
- Fix bugs in the wrap file parser tree-sitter-ini
Would it be possible to make a vscode-meson release as there are a lot of important bugfixes?
=> Bump to v4.3.3

src/tasks.ts, src/utils.ts
Run Task fails on Windows occasionally due to error 87 in creating process, this can be avoided, and manually entering env can be avoided by instead running the executable via meson's devenv
=> Run Task: Use DevEnv

src/tools/muon.ts
Newer muon puts linting output on stdout instead of stderr.
=> Use stdout for newer muon

src/formatters.ts, src/introspection.ts, src/linters.ts, src/tests.ts, src/tools/muon.ts, src/types.ts, src/utils.ts, src/version.ts
This adds some general improvements and three bug fixes, I saw when implementing #261 
Bugs:
- The meson version wasn't detected correctly, since the `g` flag was used in the regex for the version number, so the resulting `match` array was `["1.6.0"]` instead of `["1.6.0","1","6","0"]`
- The version comparison was done manually in https://github.com/mesonbuild/vscode-meson/pull/268/commits/5e9c9e961e8195dcc7276686775a2ae8e8e4abfe#diff-9a3b5396b880a25586663b03f9bda56906914991b7b43b493283eca3ccc74fc3R28 and there we only checked `version[1] < 50`, which only worked correctly before `1.0.0` (thsi never showed, since after this check we additionally check, if the returned filename is an array or not, so this only cleans this up)
- The slicing of the version for meson was done incorrectly, …
=> General improvments

CHANGELOG.md, package.json, src/formatters.ts, src/types.ts
- allow the formatting provider to be set as `auto`, this means, select the best available one
- add internal priority for formatting providers
This adds an algorithm, that searches for the best available formatter. This results in the following behavior:
- if `formatting.provider` is set to `auto` we try to find a formatter in the following order `["meson", "muon"`], if one of them is found in this order, that one is used
- if `formatting.provider` is set to a specific formatter, it only tries that one and fails, if it didn't find that one
fixes #274
Let me know, me if this solution is acceptable. The problem with the previous code is, that it wasn't really designed to handle multiple formatting providers that well.
=> feat: add more sophisticated formatter selection

src/debug/index.ts, src/extension.ts, src/tests.ts
`llvm-vs-code-extensions.lldb-dap` is the new official lldb extension. The API is largely the same
Also note that `Extension().isActive` has never been correct - it returns whether the extension has been started, not whether it is enabled in the current workspace. See https://stackoverflow.com/a/78703190
=> add lldb-dap support
