- package.json
- src/extension.ts
Add a context variable used to determine if there's a meson.build file
Use that context to hide UI elements
Fixes #26
> feature: Hide sidebar viewContainer when useless

- .github/workflows/publish.yml
> actions/publish: Also publish to the OpenVSX registry

- syntaxes/meson.tmLanguage.json
See: https://github.com/mesonbuild/meson/pull/9339https://github.com/mesonbuild/meson/pull/9339
> syntax: Add `structured_sources` function

- CHANGELOG.md
- README.md
- package.json
- src/extension.ts
- src/formatters.ts
- src/linters.ts
- src/tools/muon.ts
- src/types.ts
- src/utils.ts
A basic framework for adding further linters is also added.
> Add support for muon linter and formatter

- .github/workflows/codeql-analysis.yml
- .github/workflows/main.yml
- .github/workflows/publish.yml
> actions: restrict permissions

- package.json
- src/extension.ts
- src/meson/runners.ts
- src/tasks.ts
Adding an install task definition
> Add meson install to task definitions

- package.json
- src/extension.ts
Change the description to match new behaviour
from https://github.com/mesonbuild/vscode-meson/pull/106
> Fix description for configureOnOpen

- CHANGELOG.md
- src/extension.ts
- src/meson/runners.ts
- src/utils.ts
That file can be used by projects in their launch.json's envFile to run program inside Meson's devenv.
> Generate vscode.env file to be used by launch.json

- .vscode/launch.json
- package.json
- src/configprovider.ts
- src/utils.ts
- yarn.lock
* Add support for LLDB and VS debuggers
* Fix targets  pre launch compilation task
Depends on https://github.com/mesonbuild/vscode-meson/pull/109
> Fix automatic executable targets execution 

- src/extension.ts
Otherwise there's staleness since ce4caf62a1610b83748a689e167e4223677baa50. I just hooked the existing `changeHandler`. Seems OK, though obviously doesn't work for builddir changes...
Speaking of which, is there any plan to implement something similar to #103? I'll have to rebase it for my own needs, if not.
Thanks
> extension: refresh / clear cache if extension configuration is changed.

- package.json
- src/configprovider.ts
- src/extension.ts
- src/formatters.ts
- src/introspection.ts
- src/linters.ts
- src/tasks.ts
- src/tests.ts
- src/tools/muon.ts
- src/treeview/basenode.ts
- src/treeview/index.ts
- src/treeview/nodes/base.ts
- src/treeview/nodes/sources.ts
- src/treeview/nodes/targets.ts
- src/treeview/nodes/tests.ts
- src/treeview/nodes/toplevel.ts
- src/types.ts
- src/utils.ts
- tsconfig.json
This is the current tsconfig from https://github.com/Microsoft/vscode-generator-code with additional options:
```
noImplicitReturns
noFallthroughCasesInSwitch
noImplicitOverride
noPropertyAccessFromIndexSignature
```
Thanks
> Enable strict mode and fix up all resulting errors and warnings.

- src/tasks.ts
Broken by de6d4e91c7f8c5c74c5fb3756937c7cb1a37d847, sorry about that.
> Fix boolean logic of filter in getTask().

- src/extension.ts
> tests: rebuild tests on open only if the project is configured

- syntaxes/meson.tmLanguage.json
These should more accurately reflect their nature.
> Change scopes of builtin variables

- CHANGELOG.md
- src/lsp/swift-mesonlsp.ts
> Swift-MesonLSP: Bump to v3.0.5

- CHANGELOG.md
- src/lsp/swift-mesonlsp.ts
I reorganized the code a little bit, to make it easier to read
> Add support for Apple Silicon to Swift-MesonLSP

- CHANGELOG.md
- src/extension.ts
- src/lsp/index.ts
We just need to await from my testing.
Fixes #171
> Kill language server zombie processes

- src/tasks.ts
> ProcessExecution -> ShellExecution to fix #181.

- src/treeview/nodes/targets.ts
- src/types.ts
When exploring the project tree, I ran into this error.
> Fix "s.sources" is not iterable

- CHANGELOG.md
- src/extension.ts
- src/utils.ts
> Fix absolute build directories

- CHANGELOG.md
- src/lsp/mesonlsp.ts
Changelog: https://github.com/JCWasmx86/mesonlsp/releases/tag/v4.3.1
> Bump to v4.3.1
